spring:
  data:
    mongodb:
      database: doctor-dating
      host: localhost
      port: 27017
#      uri: mongodb://localhost:27017/dating
#      password: guest
#      username: guest

server:
  port: 80
  servlet:
    context-path: /doctor-dating
